# Site settings
title:          Astra Porta - L'actualité du groupe
description:    "L'actualité de l'entreprise Astra Porta et de ses filliales"
url:            "https://astraporta.com/blog/"

# Author
author:
  name:         Sam

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]
